### ISSUE TITLE
rlib, java 8 and Android problems.

### ISSUE THREAD

**Issue by NemesisMate** [JavaSaBr/RLib#1]
Android isn't fully supporting java 8 at the moment. Worst than that, only supports some features (with an [extra library](https://developer.android.com/guide/platform/j8-jack.html?hl=es-419)) since android 6.0. 

So, using rlib actually limits the [market share](https://developer.android.com/about/dashboards/index.html) (more of the 50% are under the 6 version)

Is there a chance to have this library being compiled with java 7?

**Comment by JavaSaBr** [comment]
Where do you use this library?

**Comment by NemesisMate** [comment]
I don't use it directly but it is needed for your tonegod-particles fork.

**Comment by JavaSaBr** [comment]
Hm, I can't downgrade the library, but I can remove using the library in
the fork...

26 июл. 2017 г. 9:23 пользователь "NemesisMate" <notifications@github.com>
написал:

**Comment by NemesisMate** [comment]
Well, It is better than nothing.

**Comment by JavaSaBr** [comment]
@NemesisMate ok, is it a critical problem for you?

**Comment by NemesisMate** [comment]
@JavaSaBr It is for the production game, but I can live without a fix for a while. In the worst case I can fork my own rlib or tonegod-particles version.

**Comment by JavaSaBr** [comment]
@NemesisMate I asked it to decide how fast I need to do it ;)

**Comment by NemesisMate** [comment]
@JavaSaBr not critical then.

**Comment by JavaSaBr** [comment]
@NemesisMate I have re-checked how many efforts I need to spend to do it... so, I need to replace a lot of things :( are you sure that you have no chance to compile it using java 8?

**Comment by JavaSaBr** [comment]
@NemesisMate what do you think about this page?
https://developer.android.com/studio/write/java8-support.html

**Comment by NemesisMate** [comment]
@JavaSaBr there says that only **API level 24 (Android 7+)** can use it for most things. If the features you use are accepted then shouldn't be any problem but I don't know your code to know. However, I would say it come with lots of limitations to have in mind and it would be harder to keep the library in a semi-8 version that works with previous android versions than just a 7 version.
When you say it is a lot of work do you talk about rlib or tonegod's particles?, if the first, couldn't you just avoid to use rlib in tonegod's just like you mentioned before?.

**Comment by JavaSaBr** [comment]
@NemesisMate I talk about tonegod library, I use rlib there in a lot of places. Also, other features from SS editor requires Java 8 :(

**Comment by NemesisMate** [comment]
@JavaSaBr the editor isn't needed to be running on android (it's a developer application and it is fine with the latest technology).

Anyway, [it doesn't seem to be that much places.](https://github.com/JavaSaBr/tonegodemitter/search?p=1&q=rlib&type=&utf8=%E2%9C%93). However, maybe I can make the change.

**Comment by JavaSaBr** [comment]
@NemesisMate about the editor, if you will use j3s(scene editor) format, you will have problem with loading it on android :(

about rlib, I will make these changes, I just wanted to say that is sadly

**Comment by NemesisMate** [comment]
@JavaSaBr I'm not really using the j3s format so it isn't a problem. I use the editor to create/modify assets but I have my own ways to compose the scene app states.
So, the j3s can rely on java 8 features, but standalone assets shouldn't be tied to a such restriction (models, materials, particles, etc)

**Comment by JavaSaBr** [comment]
@NemesisMate I agree about format, but it uses editable interfaces to work with filters/custom controls/app  states, it requires java 8

**Comment by JavaSaBr** [comment]
@NemesisMate I will solve your problem in the next release of SS editor(after 0.9.11) ;)

**Comment by NemesisMate** [comment]
@JavaSaBr I'll try it and give some feedback, thanks for your effort.

**Comment by JavaSaBr** [comment]
@NemesisMate develop branch is already without rlib.
https://github.com/JavaSaBr/tonegodemitter/tree/develop
you can use this version in your project, because this version can load saved particles from SS editor with prev. version of tonegod.emitter.

**Comment by JavaSaBr** [comment]
@NemesisMate any news? :)

**Comment by NemesisMate** [comment]
@JavaSaBr oh!, yes, I'm using the latest tonegodemitter and it is working fine for android too. Thanks!.
I'm releasing the game (alpha/beta) where I'm using the emitters soon. (i'll post it in the forums)
